import { OUTSIDE_THE_WIRE } from "../config/_outside-the-wire.mjs";

/**
 * Extend the base Actor document by defining a custom roll data structure which is ideal for the Simple system.
 * @extends {Actor}
 */
export class OutsideTheWireActor extends Actor {

  /**
   * @override
   * Augment the actor source data with additional dynamic data that isn't
   * handled by the actor's DataModel. Data calculated in this step should be
   * available both inside and outside of character sheets (such as if an actor
   * is queried and has a roll executed directly from it).
   */
  prepareDerivedData() {
    super.prepareDerivedData();
    const actorData = this;
    const flags = actorData.flags.invincible || {};
  }

  /**
   *
   * @override
   * Augment the actor's default getRollData() method by appending the data object
   * generated by the its DataModel's getRollData(), or null. This polymorphic
   * approach is useful when you have actors & items that share a parent Document,
   * but have slightly different data preparation needs.
   */
  getRollData() {
    return { ...super.getRollData(), ...(this.system.getRollData?.() ?? null) };
  }

  static getDefaultArtwork(actorData) {
    return {
      img: `systems/outside-the-wire/assets/icons/${actorData.type.toLowerCase()}.svg`,
      texture: {
        src: `systems/outside-the-wire/assets/icons/${actorData.type.toLowerCase()}.svg`
      }
    };
  }

  /** @inheritdoc */
  async _preCreate(data, options, user) {
    const allowed = await super._preCreate(data, options, user);
    if (allowed === false) return false;

    const tokenConfig = OUTSIDE_THE_WIRE.ACTOR.PROTOTYPE_TOKEN[data.type];

    if (!tokenConfig)
      return;

    const updates = foundry.utils.mergeObject({
      prototypeToken: tokenConfig,
    }, data, { insertKeys: false, insertValues: false, inplace: false });
    this.updateSource(updates);
  }
}
